development:
  secret_key_base: <%= Settings.secret_token || SecureRandom.hex(64) %>
 
test:
  secret_key_base: <%= Settings.secret_token || SecureRandom.hex(64) %>
 
production:
  secret_key_base: <%= Settings.secret_token || SecureRandom.hex(64) %>
